export  const plansData = [
        {
            "id": 103696,
            "project": "БЦ Luminor",
            "businessCenter": "luminor",
            "current_floor": 4,
            "floor_max": 12,
            "height": 4.5,
            "dealType": "Продажа и аренда",
            "propertyType": "Офис",
            "block": 3,
            "square": 160.3,
            "plan": "/assets/img/plans/160-3.svg"
        }  ,
        {
            "id": 103697,
            "project": "Icon",
            "businessCenter": "icon",
            "current_floor": 2,
            "floor_max": 8,
            "height": 4.5,
            "dealType": "Продажа и аренда",
            "propertyType": "Коммерция",
            "block": 3,
            "square": 220.4,
            "plan": "/assets/img/plans/220-4.svg"
        } ,
        {
            "id": 103698,
            "project": "БЦ Luminor",
            "businessCenter": "luminor",
            "current_floor": 4,
            "floor_max": 12,
            "height": 4.5,
            "dealType": "Продажа и аренда",
            "propertyType": "Офис",
            "block": 3,
            "square": 160.3,
            "plan": "/assets/img/plans/160-3.svg"
        },
        {
            "id": 103699,
            "project": "Icon",
            "businessCenter": "icon",
            "current_floor": 5,
            "floor_max": 8,
            "height": 4.5,
            "dealType": "Продажа и аренда",
            "propertyType": "Коммерция",
            "block": 3,
            "square": 220.4,
            "plan": "/assets/img/plans/220-4.svg"
        },
        {
            "id": 103700,
            "project": "БЦ Luminor",
            "businessCenter": "luminor",
            "current_floor": 1,
            "floor_max": 12,
            "height": 4.5,
            "dealType": "Продажа и аренда",
            "propertyType": "Офис",
            "block": 3,
            "square": 160.3,
            "plan": "/assets/img/plans/160-3.svg"
        },
        {
            "id": 103701,
            "project": "Norex",
            "businessCenter": "norex",
            "current_floor": 4,
            "floor_max": 8,
            "height": 4.5,
            "dealType": "Продажа и аренда",
            "propertyType": "Коммерция",
            "block": 3,
            "square": 220.4,
            "plan": "/assets/img/plans/220-4.svg"
        },
        {
            "id": 103702,
            "project": "БЦ Luminor",
            "businessCenter": "luminor",
            "current_floor": 6,
            "floor_max": 12,
            "height": 4.5,
            "dealType": "Продажа и аренда",
            "propertyType": "Офис",
            "block": 3,
            "square": 160.3,
            "plan": "/assets/img/plans/160-3.svg"
        },
        {
            "id": 103703,
            "project": "Norex",
            "businessCenter": "norex",
            "current_floor": 9,
            "floor_max": 12,
            "height": 4.5,
            "dealType": "Продажа и аренда",
            "propertyType": "Коммерция",
            "block": 3,
            "square": 220.4,
            "plan": "/assets/img/plans/220-4.svg"
        },
        {
            "id": 103704,
            "project": "БЦ Luminor",
            "businessCenter": "luminor",
            "current_floor": 3,
            "floor_max": 12,
            "height": 4.5,
            "dealType": "Продажа и аренда",
            "propertyType": "Офис",
            "block": 3,
            "square": 160.3,
            "plan": "/assets/img/plans/160-3.svg"
        },
        {
            "id": 103705,
            "project": "Icon",
            "businessCenter": "icon",
            "current_floor": 1,
            "floor_max": 12,
            "height": 4.5,
            "dealType": "Продажа и аренда",
            "propertyType": "Коммерция",
            "block": 3,
            "square": 220.4,
            "plan": "/assets/img/plans/220-4.svg"
        }         

    ]