export  const plansData = [
        {
            "id": 103696,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 1,
            "floor_max": 6,
            "height": 3.3,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 122.2,
            "plan": "/assets/img/plans/Icon/1/План 1 этажа - 122.2м2.webp"
        }  ,
        {
            "id": 103697,
            "project": "Icon",
            "businessCenter": "icon",
            "current_floor": 1,
            "floor_max": 6,
            "height": 3,
            "dealType": "Продажа",
            "propertyType": "Коммерция",
            "block": 3,
            "square": 164.6,
            "plan": "/assets/img/plans/Icon/1/План 1 этажа - 164.6м2.webp"
        } ,
        {
            "id": 103698,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 1,
            "floor_max": 6,
            "height": 3,
            "dealType": "Продажа",
            "propertyType": "Коммерция",
            "block": 3,
            "square": 293.9,
            "plan": "/assets/img/plans/Icon/1/План 1 этажа - 293.9м2.webp"
        },
        {
            "id": 103699,
            "project": "Icon",
            "businessCenter": "icon",
            "current_floor": 1,
            "floor_max": 6,
            "height": 3.3,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 105.8,
            "plan": "/assets/img/plans/Icon/1/План 1 этажа -105.8м2.webp"
        },
        {
            "id": 103700,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 1,
            "floor_max": 6,
            "height": 4.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 119.4,
            "plan": "/assets/img/plans/Icon/1/План 1 этажа -119.4м2.webp"
        },
        {
            "id": 103701,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 1,
            "floor_max": 6,
            "height": 3,
            "dealType": "Продажа ",
            "propertyType": "Офис",
            "block": 3,
            "square": 121.1,
            "plan": "/assets/img/plans/Icon/1/План 1 этажа -121.1м2.webp"
        },
        {
            "id": 103702,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 1,
            "floor_max": 6,
            "height": 3,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 159.7,
            "plan": "/assets/img/plans/Icon/1/План 1 этажа -159.7м2.webp"
        },
        {
            "id": 103703,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 1,
            "floor_max": 6,
            "height": 3,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 119.4,
            "plan": "/assets/img/plans/Icon/1/План 1 этажа мезонин -119.4м2.webp"
        },
        {
            "id": 103704,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 1,
            "floor_max": 6,
            "height": 3,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 121.1,
            "plan": "/assets/img/plans/Icon/1/План 1 этажа мезонин -121.1м2.webp"
        },
        {
            "id": 103705,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 1,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 122.2,
            "plan": "/assets/img/plans/Icon/1/План 1 этажа мезонин -122.2м2.webp"
        },
        {
            "id": 103706,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 1,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 159.7,
            "plan": "/assets/img/plans/Icon/1/План 1 этажа мезонин -159.7м2.webp"
        },
        {
            "id": 103707,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 1,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Коммерция",
            "block": 3,
            "square": 164.6,
            "plan": "/assets/img/plans/Icon/1/План 1 этажа мезонин -164.6м2.webp"
        },
        {
            "id": 103708,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 1,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Коммерция",
            "block": 3,
            "square": 300.3,
            "plan": "/assets/img/plans/Icon/1/План 1 этажа мезонин -300.3м2.webp"
        },
        {
            "id": 103709,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 1,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 190.7,
            "plan": "/assets/img/plans/Icon/1/План 1 этажа мезонин 190.7м2.webp"
        },
        {
            "id": 103710,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 2,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 47.3,
            "plan": "/assets/img/plans/Icon/2/План 2 этажа - 47.3м2.webp"
        },
        {
            "id": 103711,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 2,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 64.8,
            "plan": "/assets/img/plans/Icon/2/План 2 этажа - 64.8м2.webp"
        },
        {
            "id": 103711,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 2,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 66.0,
            "plan": "/assets/img/plans/Icon/2/План 2 этажа - 66.0м2.webp"
        },
        {
            "id": 103712,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 2,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 67.2,
            "plan": "/assets/img/plans/Icon/2/План 2 этажа - 67.2м2.webp"
        },
        {
            "id": 103713,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 2,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 68.7,
            "plan": "/assets/img/plans/Icon/2/План 2 этажа - 68.7м2.webp"
        },
        {
            "id": 103714,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 2,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 81.2,
            "plan": "/assets/img/plans/Icon/2/План 2 этажа - 81.2м2.webp"
        },
        {
            "id": 103715,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 2,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 98.5,
            "plan": "/assets/img/plans/Icon/2/План 2 этажа - 98.5м2.webp"
        },
        {
            "id": 103716,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 2,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 102.8,
            "plan": "/assets/img/plans/Icon/2/План 2 этажа - 102.8м2.webp"
        },
        {
            "id": 103717,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 2,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 123.0,
            "plan": "/assets/img/plans/Icon/2/План 2 этажа - 123.0м2.webp"
        },
        {
            "id": 103718,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 2,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 136.5,
            "plan": "/assets/img/plans/Icon/2/План 2 этажа - 136.5м2.webp"
        },
        {
            "id": 103719,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 2,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 202.8,
            "plan": "/assets/img/plans/Icon/2/План 2 этажа - 202.8м2.webp"
        },
        {
            "id": 103720,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 2,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 210.1,
            "plan": "/assets/img/plans/Icon/2/План 2 этажа - 210.1м2.webp"
        }
        /* */
        ,
        {
            "id": 103721,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 3,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 47.3,
            "plan": "/assets/img/plans/Icon/3/План 3 этажа - 47.3м2.webp"
        },
        {
            "id": 103722,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 3,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 58.5,
            "plan": "/assets/img/plans/Icon/3/План 3 этажа - 58.5м2.webp"
        },
        {
            "id": 103723,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 3,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 62.6,
            "plan": "/assets/img/plans/Icon/3/План 3 этажа - 62.6м2.webp"
        },
        {
            "id": 103724,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 3,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 66.0,
            "plan": "/assets/img/plans/Icon/3/План 3 этажа - 66.0м2-1.webp"
        },
        {
            "id": 103725,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 3,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 66.0,
            "plan": "/assets/img/plans/Icon/3/План 3 этажа - 66.0м2.webp"
        },
        {
            "id": 103726,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 3,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 81.2,
            "plan": "/assets/img/plans/Icon/3/План 3 этажа - 81.2м2.webp"
        },
        {
            "id": 103727,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 3,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 98.5,
            "plan": "/assets/img/plans/Icon/3/План 3 этажа - 98.5м2.webp"
        },
        {
            "id": 103728,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 3,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 102.8,
            "plan": "/assets/img/plans/Icon/3/План 3 этажа - 102.8м2.webp"
        },
        {
            "id": 103729,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 3,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 135.1,
            "plan": "/assets/img/plans/Icon/3/План 3 этажа - 135.1м2.webp"
        },
        {
            "id": 103730,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 3,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 137.8,
            "plan": "/assets/img/plans/Icon/3/План 3 этажа - 137.8м2.webp"
        },
        {
            "id": 103731,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 3,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 202.8,
            "plan": "/assets/img/plans/Icon/3/План 3 этажа - 202.8м2.webp"
        },
        {
            "id": 103732,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 3,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 210.1,
            "plan": "/assets/img/plans/Icon/3/План 3 этажа - 210.1м2.webp"
        },
        /* */
        {
            "id": 103733,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 4,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 47.3,
            "plan": "/assets/img/plans/Icon/4/План 4 этажа - 47.3м2.webp"
        },
        {
            "id": 103734,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 4,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 59.4,
            "plan": "/assets/img/plans/Icon/4/План 4 этажа - 59.4м2.webp"
        },
        {
            "id": 103735,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 4,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 61.1,
            "plan": "/assets/img/plans/Icon/4/План 4 этажа - 61.1м2.webp"
        },
        {
            "id": 103736,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 4,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 64.8,
            "plan": "/assets/img/plans/Icon/4/План 4 этажа - 64.8м2.webp"
        },
        {
            "id": 103737,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 4,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 66.0,
            "plan": "/assets/img/plans/Icon/4/План 4 этажа - 66.0м2.webp"
        },
        {
            "id": 103738,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 4,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 68.6,
            "plan": "/assets/img/plans/Icon/4/План 4 этажа - 68.6м2.webp"
        },
        {
            "id": 103739,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 4,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 81.2,
            "plan": "/assets/img/plans/Icon/4/План 4 этажа - 81.2м2.webp"
        },
        {
            "id": 103740,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 4,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 109.0,
            "plan": "/assets/img/plans/Icon/4/План 4 этажа - 109.0м2.webp"
        },
        {
            "id": 103741,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 4,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 123.0,
            "plan": "/assets/img/plans/Icon/4/План 4 этажа - 123.0м2.webp"
        },
        {
            "id": 103742,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 4,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 134.5,
            "plan": "/assets/img/plans/Icon/4/План 4 этажа - 134.5м2.webp"
        },
        {
            "id": 103743,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 4,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 189.5,
            "plan": "/assets/img/plans/Icon/4/План 4 этажа - 189.5м2.webp"
        },
        {
            "id": 103744,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 4,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 198.2,
            "plan": "/assets/img/plans/Icon/4/План 4 этажа - 198.2м2.webp"
        },
        /* */
        {
            "id": 103745,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 5,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 47.3,
            "plan": "/assets/img/plans/Icon/5/План 5 этажа - 47.3м2.webp"
        },
        {
            "id": 103746,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 5,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 64.8,
            "plan": "/assets/img/plans/Icon/5/План 5 этажа - 64.8м2.webp"
        },
        {
            "id": 103747,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 5,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 66.0,
            "plan": "/assets/img/plans/Icon/5/План 5 этажа - 66.0м2.webp"
        },
        {
            "id": 103748,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 5,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 67.1,
            "plan": "/assets/img/plans/Icon/5/План 5 этажа - 67.1м2.webp"
        },
        {
            "id": 103749,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 5,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 68.3,
            "plan": "/assets/img/plans/Icon/5/План 5 этажа - 68.3м2.webp"
        },
        {
            "id": 103750,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 5,
            "floor_max": 6,
            "height": 3.5,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 68.6,
            "plan": "/assets/img/plans/Icon/5/План 5 этажа - 68.6м2.webp"
        },
        {
            "id": 103751,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 5,
            "floor_max": 6,
            "height": 3.3,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 81.2,
            "plan": "/assets/img/plans/Icon/5/План 5 этажа - 81.2м2.webp"
        },
        {
            "id": 103752,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 5,
            "floor_max": 6,
            "height": 3.3,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 123.0,
            "plan": "/assets/img/plans/Icon/5/План 5 этажа - 123.0м2.webp"
        },
        {
            "id": 103753,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 5,
            "floor_max": 6,
            "height": 3.3,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 126.1,
            "plan": "/assets/img/plans/Icon/5/План 5 этажа - 126.1м2.webp"
        },
        {
            "id": 103754,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 5,
            "floor_max": 6,
            "height": 3,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 151.5,
            "plan": "/assets/img/plans/Icon/5/План 5 этажа - 151.5м2.webp"
        },
        {
            "id": 103755,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 5,
            "floor_max": 6,
            "height": 3,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 202.8,
            "plan": "/assets/img/plans/Icon/5/План 5 этажа - 202.8м2.webp"
        },
        {
            "id": 103756,
            "project": "БЦ Icon",
            "businessCenter": "icon",
            "current_floor": 5,
            "floor_max": 6,
            "height": 3,
            "dealType": "Продажа",
            "propertyType": "Офис",
            "block": 3,
            "square": 210.1,
            "plan": "/assets/img/plans/Icon/5/План 5 этажа - 210.1м2.webp"
        },
    ]